export const ADD_CARTS_LIST_REQUEST = 'ADD_CARTS_LIST_REQUEST';
export const ADD_CART_DETAILS_REQUEST = 'ADD_CART_DETAILS_REQUEST';
export const LOADING_CARTS = 'LOADING_CARTS';
export const LOAD_CARTS_SUCCESS = 'LOAD_CARTS_SUCCESS';
export const SET_CART_LIST_TOTAL = 'SET_CART_LIST_TOTAL';
export const SET_CARTS_LIST_CURRENT_PAGE = 'SET_CARTS_LIST_CURRENT_PAGE';
export const SET_CARTS_DETAILS_CURRENT_PAGE = 'SET_CARTS_DETAILS_CURRENT_PAGE';
export const LOAD_CARTS_FAILURE = 'LOAD_CARTS_FAILURE';
export const LOADING_CART_DETAILS = 'LOADING_CART_DETAILS';
export const GET_CART_ITEMS_SUCCESS = 'GET_CART_ITEMS_SUCCESS';
export const SET_CART_ITEMS_LIST_TOTAL = 'SET_CART_ITEMS_LIST_TOTAL';
export const GET_CART_ITEMS_FAILURE = 'GET_CART_ITEMS_FAILURE';

export const baseUrl = `${process.env.REACT_APP_API_URL}/carts`;
