export const LOADING_CARTS = 'LOADING_CARTS';
export const LOAD_CARTS_SUCCESS = 'LOAD_CARTS_SUCCESS';
export const LOAD_CARTS_FAILURE = 'LOAD_CARTS_FAILURE';
export const LOADING_CART_DETAILS = 'LOADING_CART_DETAILS';
export const GET_CART_ITEMS_SUCCESS = 'GET_CART_ITEMS_SUCCESS';
export const GET_CART_ITEMS_FAILURE = 'GET_CART_ITEMS_FAILURE';

export const baseUrl = `${process.env.REACT_APP_API_URL}/carts`;
