export const LOADING_CATALOGS = 'LOADING_CATALOGS';
export const LOAD_CATALOGS_SUCCESS = 'LOAD_CATALOGS_SUCCESS';
export const SET_CATALOGS_LIST_TOTAL = 'SET_CATALOGS_LIST_TOTAL';
export const ADD_CATALOGS_LIST_REQUEST = 'ADD_CATALOGS_LIST_REQUEST';
export const SET_CATALOGS_LIST_CURRENT_PAGE = 'SET_CATALOGS_LIST_CURRENT_PAGE';
export const LOAD_CATALOGS_FAILURE = 'LOAD_CATALOGS_FAILURE';
export const CREATING_CATALOG = 'CREATING_CATALOG';
export const CREATE_CATALOG_SUCCESS = 'CREATE_CATALOG_SUCCESS';
export const CREATE_CATALOG_FAILURE = 'CREATE_CATALOG_FAILURE';
export const UPDATING_CATALOG = 'UPDATING_CATALOG';
export const UPDATE_CATALOG_SUCCESS = 'UPDATE_CATALOG_SUCCESS';
export const UPDATE_CATALOG_FAILURE = 'UPDATE_CATALOG_FAILURE';
export const DELETING_CATALOG = 'DELETING_CATALOG';
export const DELETE_CATALOG_SUCCESS = 'DELETE_CATALOG_SUCCESS';
export const DELETE_CATALOG_FAILURE = 'DELETE_CATALOG_FAILURE';

export const baseUrl = `${process.env.REACT_APP_API_URL}/catalogs`;
