export const ADD_CURRENCY = 'ADD_CURRENCY';
export const ADD_CURRENCIES = 'ADD_CURRENCIES';
export const SET_CURRENCY_LOADING = 'SET_CURRENCY_LOADING';
export const SET_CURRENCY_REQUEST = 'SET_CURRENCY_REQUEST';
export const SET_CURRENCY_IDS = 'SET_CURRENCY_IDS';
export const RESET_CURRENCY = 'RESET_CURRENCY';

export const CURRENCY_API = `/currencies`;
