export const LOADING_CURRENCIES = 'LOADING_CURRENCIES';
export const LOAD_CURRENCIES_SUCCESS = 'LOAD_CURRENCIES_SUCCESS';
export const LOAD_CURRENCIES_FAILURE = 'LOAD_CURRENCIES_FAILURE';
export const CREATING_CURRENCY = 'CREATING_CURRENCY';
export const CREATE_CURRENCY_SUCCESS = 'CREATE_CURRENCY_SUCCESS';
export const CREATE_CURRENCY_FAILURE = 'CREATE_CURRENCY_FAILURE';
export const UPDATING_CURRENCY = 'UPDATING_CURRENCY';
export const UPDATE_CURRENCY_SUCCESS = 'UPDATE_CURRENCY_SUCCESS';
export const UPDATE_CURRENCY_FAILURE = 'UPDATE_CURRENCY_FAILURE';
export const DELETING_CURRENCY = 'DELETING_CURRENCY';
export const DELETE_CURRENCY_SUCCESS = 'DELETE_CURRENCY_SUCCESS';
export const DELETE_CURRENCY_FAILURE = 'DELETE_CURRENCY_FAILURE';

export const baseUrl = `${process.env.REACT_APP_API_URL}/currencies`;
