export const ADD_MEMBERSHIP = 'ADD_MEMBERSHIP';
export const ADD_MEMBERSHIPS = 'ADD_MEMBERSHIPS';
export const SET_MEMBERSHIP_LOADING = 'SET_MEMBERSHIP_LOADING';
export const SET_MEMBERSHIP_REQUEST = 'SET_MEMBERSHIP_REQUEST';
export const SET_MEMBERSHIP_IDS = 'SET_MEMBERSHIP_IDS';
export const RESET_MEMBERSHIP = 'RESET_MEMBERSHIP';

export const MEMBERSHIP_API = `${process.env.REACT_APP_API_URL}/memberships`;
