export const ADD_MEMBERSHIPS_LIST_REQUEST = 'ADD_MEMBERSHIPS_LIST_REQUEST';
export const LOADING_MEMBERSHIPS = 'LOADING_MEMBERSHIPS';
export const LOAD_MEMBERSHIPS_SUCCESS = 'LOAD_MEMBERSHIPS_SUCCESS';
export const LOAD_MEMBERSHIPS_FAILURE = 'LOAD_MEMBERSHIPS_FAILURE';
export const SET_MEMBERSHIPS_LIST_TOTAL = 'SET_MEMBERSHIPS_LIST_TOTAL';
export const SET_MEMEBERSHIPS_LIST_CURRENT_PAGE = 'SET_MEMEBERSHIPS_LIST_CURRENT_PAGE';

export const baseUrl = `${process.env.REACT_APP_API_URL}/memberships`;
