export const LOADING_ORDERS = 'LOADING_ORDERS';
export const LOADING_ORDER_DETAILS = 'LOADING_ORDER_DETAILS';
export const LOADING_ORDER_ITEMS = 'LOADING_ORDER_ITEMS';
export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS';
export const LOAD_ORDERS_FAILURE = 'LOAD_ORDERS_FAILURE';
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_FAILURE = 'GET_ORDER_DETAILS_FAILURE';
export const GET_ORDER_ITEMS_SUCCESS = 'GET_ORDER_ITEMS_SUCCESS';
export const GET_ORDER_ITEMS_FAILURE = 'GET_ORDER_ITEMS_FAILURE';

export const baseUrl = `${process.env.REACT_APP_API_URL}/orders`;
