export const ADD_PAYMENTS = 'ADD_PAYMENTS';
export const SET_PAYMENT_LOADING = 'SET_PAYMENT_LOADING';
export const SET_PAYMENT_REQUEST = 'SET_PAYMENT_REQUEST';
export const SET_PAYMENT_IDS = 'SET_PAYMENT_IDS';

export const PAYMENT_API = `/payments`;
