export const ADD_PAYMENTS_LIST_REQUEST = 'ADD_PAYMENTS_LIST_REQUEST';
export const SET_PAYMENTS_LIST_CURRENT_PAGE = 'SET_PAYMENTS_LIST_CURRENT_PAGE';
export const LOADING_PAYMENTS = 'LOADING_PAYMENTS';
export const LOAD_PAYMENTS_SUCCESS = 'LOAD_PAYMENTS_SUCCESS';
export const LOAD_PAYMENTS_FAILURE = 'LOAD_PAYMENTS_FAILURE';
export const SET_PAYMENTS_LIST_TOTAL = 'SET_PAYMENTS_LIST_TOTAL';

export const baseUrl = `${process.env.REACT_APP_API_URL}/payments`;
