export const LOADING_PLANS = 'LOADING_PLANS';
export const LOAD_PLANS_SUCCESS = 'LOAD_PLANS_SUCCESS';
export const SET_PLANS_LIST_TOTAL = 'SET_PLANS_LIST_TOTAL';
export const LOAD_PLANS_FAILURE = 'LOAD_PLANS_FAILURE';
export const CREATING_PLAN = 'CREATING_PLAN';
export const CREATE_PLAN_SUCCESS = 'CREATE_PLAN_SUCCESS';
export const CREATE_PLAN_FAILURE = 'CREATE_PLAN_FAILURE';
export const UPDATING_PLAN = 'UPDATING_PLAN';
export const UPDATE_PLAN_SUCCESS = 'UPDATE_PLAN_SUCCESS';
export const UPDATE_PLAN_FAILURE = 'UPDATE_PLAN_FAILURE';
export const DELETING_PLAN = 'DELETING_PLAN';
export const DELETE_PLAN_SUCCESS = 'DELETE_PLAN_SUCCESS';
export const DELETE_PLAN_FAILURE = 'DELETE_PLAN_FAILURE';

export const baseUrl = `${process.env.REACT_APP_API_URL}/plans`;
