export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const SET_PRODUCT_LOADING = 'SET_PRODUCT_LOADING';
export const SET_PRODUCT_REQUEST = 'SET_PRODUCT_REQUEST';
export const SET_PRODUCT_IDS = 'SET_PRODUCT_IDS';
export const RESET_PRODUCT = 'RESET_PRODUCT';

export const PRODUCT_API = `/products`;
