export const LOADING_PRODUCT_TYPES = 'LOADING_PRODUCT_TYPES';
export const LOAD_PRODUCT_TYPES_SUCCESS = 'LOAD_PRODUCT_TYPES_SUCCESS';
export const SET_PRODUCT_TYPES_LIST_TOTAL = 'SET_PRODUCT_TYPES_LIST_TOTAL';
export const LOAD_PRODUCT_TYPES_FAILURE = 'LOAD_PRODUCT_TYPES_FAILURE';
export const CREATING_PRODUCT_TYPE = 'CREATING_PRODUCT_TYPE';
export const CREATE_PRODUCT_TYPE_SUCCESS = 'CREATE_PRODUCT_TYPE_SUCCESS';
export const CREATE_PRODUCT_TYPE_FAILURE = 'CREATE_PRODUCT_TYPE_FAILURE';
export const UPDATING_PRODUCT_TYPE = 'UPDATING_PRODUCT_TYPE';
export const UPDATE_PRODUCT_TYPE_SUCCESS = 'UPDATE_PRODUCT_TYPE_SUCCESS';
export const UPDATE_PRODUCT_TYPE_FAILURE = 'UPDATE_PRODUCT_TYPE_FAILURE';
export const DELETING_PRODUCT_TYPE = 'DELETING_PRODUCT_TYPE';
export const DELETE_PRODUCT_TYPE_SUCCESS = 'DELETE_PRODUCT_TYPE_SUCCESS';
export const DELETE_PRODUCT_TYPE_FAILURE = 'DELETE_PRODUCT_TYPE_FAILURE';

export const baseUrl = `${process.env.REACT_APP_API_URL}/types`;
